language: ruby
rvm:
- 2.1.5
env:
  - DB=postgresql
before_script:
  - bundle exec rake db:create RAILS_ENV=test
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
bundler_args: "--without production"
notifications:
  slack:
    secure: aObmYdbc5gcPCHcXBdSIgiVNlugePt7pekg3AQUuL1LJcZCBSCV1Q+no3f1wGwI90fTJyRVJ8CMVoqcfnWyS5bFEv4p25BYuwbgsslrkh7sULN696Nyh9nYLovtuE1qoAKesKiA78ex2rTQnLJbQMcnorqe8I5o86fvJb9UmKpI=
addons:
  code_climate:
    repo_token: 9cb9de0551456dd90386347ae171b265ae47460577175e5b10778bcd1b6262ee