# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9472e340d872a9147bf5a2b919b23783621fda728b2687400e3b0169289e3490759f070099d090dc812f9b3be07bf7db44e4fa51530ef13d0b6ec8aa0014b08

test:
  secret_key_base: f218ece59bfd204e29d112846ffcbcbe7671eabdf917dbcf7cd0ee4794e06fb6af68866a09bdb517a78b66125f5d8909099a4be169b421922659cf2d2ec48f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
