development:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') { '3b7cd727ee24e8444053437c36cc66c3' } %>

test:
  secret_key_base: abcdefgabcdefgabcdefgabcdefgabcd

production:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>